name = "toyvo_modded"
author = "toyvo"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e5c133a5479e4dd3ad67067b07f256c47da8d6a9d39e671148df57f00e9a6ad7"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
